language csharp
dist trusty
sudo required
mono none
dotnet 2.1.5
script
- dotnet restore -s httpsdotnet.myget.orgFaspnetcore-devapiv3index.json -s
httpsapi.nuget.orgv3index.json
- dotnet test ./ASC.Tests/ASC.Tests.csproj
- dotnet build